# Generated by Django 5.2.18 on 2026-10-07 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0006_alter_stockmovement_conversion_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nome")),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Notas internas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("unit", models.CharField(max_length=40)),
                ("base_quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("conversion_snapshot", models.JSONField(default=dict)),
                (
                    "manual_unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialAlternative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.material",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alternatives",
                        to="projects.projectmaterial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("technique", models.CharField(blank=True, max_length=100)),
                ("base_quantity", models.PositiveIntegerField(default=1)),
                ("estimated_seconds", models.PositiveIntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "additional_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("markup", "Markup"), ("margin", "Margem")],
                        default="markup",
                        max_length=10,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=4, default=".5", max_digits=7),
                ),
                ("fee", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectmaterial",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="projects.projectrevision",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="current_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for",
                to="projects.projectrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrevision",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="project_revision_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_quantity__gt", 0),
                    ("hourly_rate__gte", 0),
                    ("additional_cost__gte", 0),
                ),
                name="project_revision_valid_cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0), ("base_quantity__gt", 0)),
                name="project_material_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manual_unit_cost__isnull", True),
                    ("manual_unit_cost__gte", 0),
                    _connector="OR",
                ),
                name="project_material_manual_cost_valid",
            ),
        ),
    ]
