# Generated by Django 5.2.18 on 2026-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrevision',
            name='reference_policy',
            field=models.CharField(choices=[('available', 'Média do estoque disponível'), ('latest', 'Última camada registrada'), ('manual', 'Referência manual da ficha')], default='available', max_length=12, verbose_name='Referência de custo'),
        ),
    ]
