# Generated by Django 5.2.18 on 2026-10-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrevision_reference_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrevision',
            name='quick_entry',
            field=models.BooleanField(default=False),
        ),
    ]
