# Generated by Django 5.2.18 on 2026-10-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("production", "0001_initial"),
        ("sales", "0004_quoteitem_line_key_quoteversion_amends_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentallocation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="production.order",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation",
                to="finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="sales.quoteversion",
            ),
        ),
        migrations.AddField(
            model_name="receivable",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivables",
                to="production.order",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="finance.paymentallocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="allocation_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivable",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="receivable_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_positive"
            ),
        ),
    ]
