# Generated by Django 5.2.18 on 2026-10-07 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('yarn', 'Fio'), ('fabric', 'Tecido'), ('filling', 'Enchimento'), ('accessory', 'Acessório'), ('packaging', 'Embalagem'), ('other', 'Outro material')], max_length=20, verbose_name='Tipo')),
                ('unit', models.CharField(choices=[('g', 'Gramas (g)'), ('m', 'Metros (m)'), ('un', 'Unidades (un)')], max_length=2, verbose_name='Unidade de estoque')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Cor')),
                ('color_code', models.CharField(blank=True, max_length=40, verbose_name='Código da cor')),
                ('tex', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Tex (somente fios)')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantidade')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Custo por unidade base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Estoque inicial', max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='materials.material')),
            ],
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['owner', 'name'], name='materials_m_owner_i_1c9ac0_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('tex__isnull', True), ('tex__gt', 0), _connector='OR'), name='material_positive_tex'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='opening_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='opening_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('material',), name='one_opening_per_material'),
        ),
    ]
