# Generated by Django 5.2.18 on 2026-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_request_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Custo por unidade base'),
        ),
    ]
