# Generated by Django 5.2.18 on 2026-10-07 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_stockmovement_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lot",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Lote de fabricação"
                    ),
                ),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("physical", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "reserved",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("factor", models.DecimalField(decimal_places=6, max_digits=12)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReservationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reserve", "Reserva"),
                            ("consume", "Consumo reservado"),
                            ("release", "Liberação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.UUIDField()),
                ("action", models.CharField(max_length=40)),
                ("payload_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("remaining", models.DecimalField(decimal_places=6, max_digits=12)),
                ("reference", models.UUIDField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="opening_quantity_positive",
        ),
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="one_opening_per_material",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="conversion_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("opening", "Estoque inicial"),
                    ("receipt", "Recebimento"),
                    ("consumption", "Consumo"),
                    ("loss", "Perda"),
                    ("return", "Sobra recuperada"),
                    ("adjustment", "Ajuste"),
                ],
                default="opening",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="costlayer",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="layers",
                to="materials.material",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="layer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="materials.costlayer",
            ),
        ),
        migrations.AddField(
            model_name="materialconversion",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversions",
                to="materials.material",
            ),
        ),
        migrations.AddField(
            model_name="stockoperation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.stockoperation",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="operation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="materials.stockoperation",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="movement_quantity_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "opening"), _negated=True),
                    ("quantity__gt", 0),
                    _connector="OR",
                ),
                name="opening_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "opening")),
                fields=("material",),
                name="one_opening_per_material",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="materials.costlayer",
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="materials.stockreservation",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("physical__gte", 0)),
                name="layer_physical_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__gte", 0)),
                name="layer_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("physical"))),
                name="layer_reserved_within_physical",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_quantity__gt", 0)),
                name="layer_original_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_cost__isnull", True), ("unit_cost__gte", 0), _connector="OR"
                ),
                name="layer_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialconversion",
            constraint=models.UniqueConstraint(
                fields=("material", "name", "version"), name="conversion_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialconversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("factor__gt", 0)), name="conversion_positive_factor"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockoperation",
            constraint=models.UniqueConstraint(
                fields=("owner", "key"), name="stock_operation_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="reservation_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("remaining__gte", 0), ("remaining__lte", models.F("quantity"))
                ),
                name="reservation_remaining_valid",
            ),
        ),
    ]
