# Generated by Django 5.2.18 on 2026-10-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_backfill_opening_layers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="conversion_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="materials.costlayer",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="materials.stockoperation",
            ),
        ),
    ]
