# Generated by Django 5.2.18 on 2026-10-07 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_stockmovement_conversion_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="composition",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Composição"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=12,
                verbose_name="Estoque mínimo disponível",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="recommended_hook",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Agulha recomendada"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="thickness",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Espessura / título comercial"
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock__gte", 0)),
                name="material_minimum_stock_nonnegative",
            ),
        ),
    ]
