# Generated by Django 5.2.18 on 2026-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_material_composition_material_minimum_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
