# Generated by Django 5.2.18 on 2026-10-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_material_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='materials.stockmovement'),
        ),
    ]
