# Generated by Django 5.2.18 on 2026-10-07 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0006_alter_stockmovement_conversion_snapshot_and_more"),
        ("sales", "0004_quoteitem_line_key_quoteversion_amends_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Aguardando"),
                            ("in_progress", "Em produção"),
                            ("paused", "Pausada"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("not_sent", "Não enviada"),
                            ("ready", "Pronta para retirada"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregue"),
                        ],
                        default="not_sent",
                        max_length=20,
                    ),
                ),
                (
                    "production_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo de produção"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initial_order",
                        to="sales.quoteversion",
                    ),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_orders",
                        to="sales.quoteversion",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_key", models.UUIDField(default=uuid.uuid4)),
                ("description", models.CharField(max_length=300)),
                ("quantity", models.PositiveIntegerField()),
                ("produced", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="production.order",
                    ),
                ),
                (
                    "source_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.quoteitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="production.orderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.stockmovement",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumptions",
                        to="production.orderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("seconds", models.PositiveIntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("timer", "Cronômetro"), ("manual", "Manual")],
                        default="timer",
                        max_length=12,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="production.orderitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seconds", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="production.productionsession",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("produced__lte", models.F("quantity")),
                    ("delivered__lte", models.F("produced")),
                ),
                name="order_item_progress_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "line_key"), name="order_line_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("owner",),
                name="one_active_session_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("ended_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="session_timestamps_valid",
            ),
        ),
    ]
