# Generated by Django 5.2.18 on 2026-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_expense_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
