# Generated by Django 5.2.18 on 2026-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_orderitem_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='planned_start',
            field=models.DateField(blank=True, null=True, verbose_name='Início planejado'),
        ),
    ]
