# Generated by Django 5.2.18 on 2026-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="allocation_mode",
            field=models.CharField(
                choices=[("auto", "Proporcional"), ("manual", "Manual")],
                default="auto",
                max_length=10,
            ),
        ),
    ]
