# Generated by Django 5.2.18 on 2026-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("sent", "Enviada"),
                    ("imported", "Histórico importado"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
