# Generated by Django 5.2.18 on 2026-10-07 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nome")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Contato"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Notas internas"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.client",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuoteVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("sent", "Enviada"),
                            ("approved", "Aprovada"),
                            ("declined", "Recusada"),
                            ("changes", "Alteração solicitada"),
                            ("expired", "Expirada"),
                            ("revoked", "Revogada"),
                            ("superseded", "Substituída"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True,
                        max_length=3000,
                        verbose_name="Condições para o cliente",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo de entrega/retirada"
                    ),
                ),
                ("valid_days", models.PositiveIntegerField(default=15)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("public_snapshot", models.JSONField(blank=True, default=dict)),
                ("internal_snapshot", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("pdf", models.BinaryField(blank=True, default=bytes)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_hash", models.CharField(blank=True, max_length=64)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="sales.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=300)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "calculated_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "manual_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "project_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.projectrevision",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sales.quoteversion",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QuoteEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("key", models.UUIDField(blank=True, null=True)),
                ("declaration", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="sales.quoteversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="current_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for",
                to="sales.quoteversion",
            ),
        ),
        migrations.CreateModel(
            name="ShareToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens",
                        to="sales.quoteversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="quoteversion",
            constraint=models.UniqueConstraint(
                fields=("quote", "number"), name="quote_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0), ("valid_days__gt", 0)),
                name="quote_version_valid_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0), ("quantity__gt", 0)),
                name="quote_item_valid_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("key__isnull", False)),
                fields=("version", "key"),
                name="portal_request_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(
                fields=("owner", "number"), name="quote_number_per_owner"
            ),
        ),
    ]
