# Generated by Django 5.2.18 on 2026-10-07 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_refresh_guard_functions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="line_key",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="quoteversion",
            name="amends_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amendments",
                to="sales.quoteversion",
            ),
        ),
    ]
