# Generated by Django 5.2.18 on 2026-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_image_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteversion",
            name="approval_origin",
            field=models.CharField(
                choices=[
                    ("link", "Aceite por link"),
                    ("imported", "Histórico importado"),
                ],
                default="link",
                max_length=12,
            ),
        ),
    ]
